# Generated by Django 3.0.6 on 2020-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('product_code', models.CharField(max_length=50, verbose_name='product_code')),
                ('product_name', models.CharField(max_length=50, unique=True, verbose_name='product_name')),
                ('tamil_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='tamil_name')),
                ('product_quantity', models.CharField(max_length=50, verbose_name='product_quantity')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
                ('agency_name', models.CharField(max_length=50, verbose_name='agency_name')),
                ('old_price', models.CharField(max_length=50, verbose_name='old_price')),
                ('new_price_changing_date', models.CharField(max_length=50, verbose_name='new_price_changing_date')),
                ('product_added_date', models.CharField(max_length=50, verbose_name='product_added_date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
