# Generated by Django 3.0.6 on 2020-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsetting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='product_code'),
        ),
    ]
